[package]
name = "woodpile-dts"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
serde = { workspace = true }
proc-macro2 = { workspace = true }
convert_case = { workspace = true }
[dev-dependencies]
serde_derive = { workspace = true }
