name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run test

    steps:
    - uses: actions/checkout@v2
    - uses: buildjet/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/setup-node@v2
      with:
        node-version: "20"
        cache: "npm"
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: llvm-tools-preview
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: install
      run: |
        npm install -g npm@latest
        npm ci
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        rustup target add wasm32-wasi
        rustup target add wasm32-unknown-unknown
    - name: test
      run: |
        npm test
    - name: build
      run: |
        cargo check